### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by yang-datong** [NeatMonster/slabdbg#3]
错误在File "~/slabdbg/slabdbg.py", line 495, in <module>

**Comment by aftermathdigital** [comment]
gef➤  source ~/tools/slabdbg-master/slabdbg.py
Traceback (most recent call last):
  File "/home/user/tools/slabdbg-master/slabdbg.py", line 493, in <module>
    Slab()
  File "/home/user/tools/slabdbg-master/slabdbg.py", line 98, in __init__
    self.memstart_addr = gdb.lookup_global_symbol("memstart_addr").value()
AttributeError: 'NoneType' object has no attribute 'value'
gef➤  info sym memstart_addr
No symbol "memstart_addr" in current context.

Likewise

**Comment by fidgetingbits** [comment]
what kernel version?

**Comment by NeatMonster** [comment]
Sorry, I haven't been maintaining this project for a long time now.

You should probably use one of these alternatives instead: [libslub](https://github.com/nccgroup/libslub), [pwndbg](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/slab.py), or [drgn](https://github.com/osandov/drgn/blob/main/drgn/helpers/linux/slab.py).

**Comment by fidgetingbits** [comment]
fwiw I think this likely affects libslub as well (I'm one of the developers), so you can feel free to post a new issue there with the affected kernel version and I'll hopefully get some time to look at it.
